# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ae2328da4d8da9fa19526c07059f8c29fbbd71d9c964320b987f587461a41bcb8352ed5691ac38a9c4025af07447be6706082d5435c0a9afab5f84923db39b9

test:
  secret_key_base: e791cd087be9e3bd388c633400337a93ae7d9a090157a9e06637d9f66426d7f2badbfcab04b6cb1cf51147f43a5501b66e38f82a8b0bb805ed49d7776acbca7e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
